name: flutter_easyform_builder
description: "A Flutter package for creating beautiful forms with minimal code. Supports various field types (text, email, password, number, alphanum, datepicker) with built-in validation and extensive customization options."
version: 0.0.1
homepage: https://github.com/Riyaaaaan/flutter_easyform_builder
repository: https://github.com/Riyaaaaan/flutter_easyform_builder

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
